// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZOXgZ_E10iGuN7Ee5MnDcW_IR1FUPPI',
    appId: '1:695499409370:web:1b81d45ebdf2fa5fb9a2e3',
    messagingSenderId: '695499409370',
    projectId: 'englishcoach-2020',
    authDomain: 'englishcoach-2020.firebaseapp.com',
    databaseURL: 'https://englishcoach-2020.firebaseio.com',
    storageBucket: 'englishcoach-2020.appspot.com',
    measurementId: 'G-W1TL92CXHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9i65vSlUnEvDRkNtujVYXsv6IEO9SHY4',
    appId: '1:695499409370:android:9fd581831c0c9adeb9a2e3',
    messagingSenderId: '695499409370',
    projectId: 'englishcoach-2020',
    databaseURL: 'https://englishcoach-2020.firebaseio.com',
    storageBucket: 'englishcoach-2020.appspot.com',
  );
}
